CREATE TABLE IF NOT EXISTS user (
	Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    First_Name VARCHAR(20) NOT NULL,
    Last_Name VARCHAR(20) NOT NULL,
    Email VARCHAR(35) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS category(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Name VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Description VARCHAR(255) NOT NULL,
Price FLOAT NOT NULL,
Is_sold BOOLEAN DEFAULT false,
categoryId INT NOT NULL,
FOREIGN KEY (categoryId) REFERENCES category(Id)
);

CREATE TABLE IF NOT EXISTS cart(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
userId INT NOT NULL,
productId INT NOT NULL,
FOREIGN KEY (userId) REFERENCES user(Id),
FOREIGN KEY (productId) REFERENCES product(Id)
);